// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: recordcleaner.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecordCleanerService_GetClean_FullMethodName = "/recordcleaner.RecordCleanerService/GetClean"
	RecordCleanerService_Service_FullMethodName  = "/recordcleaner.RecordCleanerService/Service"
)

// RecordCleanerServiceClient is the client API for RecordCleanerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecordCleanerServiceClient interface {
	GetClean(ctx context.Context, in *GetCleanRequest, opts ...grpc.CallOption) (*GetCleanResponse, error)
	Service(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error)
}

type recordCleanerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordCleanerServiceClient(cc grpc.ClientConnInterface) RecordCleanerServiceClient {
	return &recordCleanerServiceClient{cc}
}

func (c *recordCleanerServiceClient) GetClean(ctx context.Context, in *GetCleanRequest, opts ...grpc.CallOption) (*GetCleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCleanResponse)
	err := c.cc.Invoke(ctx, RecordCleanerService_GetClean_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordCleanerServiceClient) Service(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, RecordCleanerService_Service_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordCleanerServiceServer is the server API for RecordCleanerService service.
// All implementations should embed UnimplementedRecordCleanerServiceServer
// for forward compatibility.
type RecordCleanerServiceServer interface {
	GetClean(context.Context, *GetCleanRequest) (*GetCleanResponse, error)
	Service(context.Context, *ServiceRequest) (*ServiceResponse, error)
}

// UnimplementedRecordCleanerServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecordCleanerServiceServer struct{}

func (UnimplementedRecordCleanerServiceServer) GetClean(context.Context, *GetCleanRequest) (*GetCleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClean not implemented")
}
func (UnimplementedRecordCleanerServiceServer) Service(context.Context, *ServiceRequest) (*ServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Service not implemented")
}
func (UnimplementedRecordCleanerServiceServer) testEmbeddedByValue() {}

// UnsafeRecordCleanerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecordCleanerServiceServer will
// result in compilation errors.
type UnsafeRecordCleanerServiceServer interface {
	mustEmbedUnimplementedRecordCleanerServiceServer()
}

func RegisterRecordCleanerServiceServer(s grpc.ServiceRegistrar, srv RecordCleanerServiceServer) {
	// If the following call panics, it indicates UnimplementedRecordCleanerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecordCleanerService_ServiceDesc, srv)
}

func _RecordCleanerService_GetClean_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCleanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordCleanerServiceServer).GetClean(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordCleanerService_GetClean_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordCleanerServiceServer).GetClean(ctx, req.(*GetCleanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordCleanerService_Service_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordCleanerServiceServer).Service(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordCleanerService_Service_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordCleanerServiceServer).Service(ctx, req.(*ServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecordCleanerService_ServiceDesc is the grpc.ServiceDesc for RecordCleanerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecordCleanerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recordcleaner.RecordCleanerService",
	HandlerType: (*RecordCleanerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClean",
			Handler:    _RecordCleanerService_GetClean_Handler,
		},
		{
			MethodName: "Service",
			Handler:    _RecordCleanerService_Service_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recordcleaner.proto",
}
