// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: recordcleaner.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	LastCleanTime       map[int32]int64        `protobuf:"bytes,1,rep,name=last_clean_time,json=lastCleanTime,proto3" json:"last_clean_time,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	CurrentCount        int32                  `protobuf:"varint,2,opt,name=current_count,json=currentCount,proto3" json:"current_count,omitempty"`
	LastWater           int64                  `protobuf:"varint,3,opt,name=last_water,json=lastWater,proto3" json:"last_water,omitempty"`
	LastFilter          int64                  `protobuf:"varint,4,opt,name=last_filter,json=lastFilter,proto3" json:"last_filter,omitempty"`
	DayOfYear           int32                  `protobuf:"varint,5,opt,name=day_of_year,json=dayOfYear,proto3" json:"day_of_year,omitempty"`
	DayCount            int32                  `protobuf:"varint,6,opt,name=day_count,json=dayCount,proto3" json:"day_count,omitempty"`
	CurrentBoxPick      int32                  `protobuf:"varint,7,opt,name=current_box_pick,json=currentBoxPick,proto3" json:"current_box_pick,omitempty"`
	DayCategoryCount    map[int32]string       `protobuf:"bytes,8,rep,name=day_category_count,json=dayCategoryCount,proto3" json:"day_category_count,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LastRelevantClean   int64                  `protobuf:"varint,9,opt,name=last_relevant_clean,json=lastRelevantClean,proto3" json:"last_relevant_clean,omitempty"`
	NonPreValidateClean int32                  `protobuf:"varint,10,opt,name=non_pre_validate_clean,json=nonPreValidateClean,proto3" json:"non_pre_validate_clean,omitempty"`
	OutOfSleeves        bool                   `protobuf:"varint,11,opt,name=out_of_sleeves,json=outOfSleeves,proto3" json:"out_of_sleeves,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_recordcleaner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_recordcleaner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_recordcleaner_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetLastCleanTime() map[int32]int64 {
	if x != nil {
		return x.LastCleanTime
	}
	return nil
}

func (x *Config) GetCurrentCount() int32 {
	if x != nil {
		return x.CurrentCount
	}
	return 0
}

func (x *Config) GetLastWater() int64 {
	if x != nil {
		return x.LastWater
	}
	return 0
}

func (x *Config) GetLastFilter() int64 {
	if x != nil {
		return x.LastFilter
	}
	return 0
}

func (x *Config) GetDayOfYear() int32 {
	if x != nil {
		return x.DayOfYear
	}
	return 0
}

func (x *Config) GetDayCount() int32 {
	if x != nil {
		return x.DayCount
	}
	return 0
}

func (x *Config) GetCurrentBoxPick() int32 {
	if x != nil {
		return x.CurrentBoxPick
	}
	return 0
}

func (x *Config) GetDayCategoryCount() map[int32]string {
	if x != nil {
		return x.DayCategoryCount
	}
	return nil
}

func (x *Config) GetLastRelevantClean() int64 {
	if x != nil {
		return x.LastRelevantClean
	}
	return 0
}

func (x *Config) GetNonPreValidateClean() int32 {
	if x != nil {
		return x.NonPreValidateClean
	}
	return 0
}

func (x *Config) GetOutOfSleeves() bool {
	if x != nil {
		return x.OutOfSleeves
	}
	return false
}

type GetCleanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncludeSeen   bool                   `protobuf:"varint,1,opt,name=include_seen,json=includeSeen,proto3" json:"include_seen,omitempty"`
	OnlyEssential bool                   `protobuf:"varint,2,opt,name=only_essential,json=onlyEssential,proto3" json:"only_essential,omitempty"`
	Peek          bool                   `protobuf:"varint,3,opt,name=peek,proto3" json:"peek,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCleanRequest) Reset() {
	*x = GetCleanRequest{}
	mi := &file_recordcleaner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCleanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCleanRequest) ProtoMessage() {}

func (x *GetCleanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recordcleaner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCleanRequest.ProtoReflect.Descriptor instead.
func (*GetCleanRequest) Descriptor() ([]byte, []int) {
	return file_recordcleaner_proto_rawDescGZIP(), []int{1}
}

func (x *GetCleanRequest) GetIncludeSeen() bool {
	if x != nil {
		return x.IncludeSeen
	}
	return false
}

func (x *GetCleanRequest) GetOnlyEssential() bool {
	if x != nil {
		return x.OnlyEssential
	}
	return false
}

func (x *GetCleanRequest) GetPeek() bool {
	if x != nil {
		return x.Peek
	}
	return false
}

type GetCleanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    int32                  `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Seen          []int32                `protobuf:"varint,2,rep,packed,name=seen,proto3" json:"seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCleanResponse) Reset() {
	*x = GetCleanResponse{}
	mi := &file_recordcleaner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCleanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCleanResponse) ProtoMessage() {}

func (x *GetCleanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recordcleaner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCleanResponse.ProtoReflect.Descriptor instead.
func (*GetCleanResponse) Descriptor() ([]byte, []int) {
	return file_recordcleaner_proto_rawDescGZIP(), []int{2}
}

func (x *GetCleanResponse) GetInstanceId() int32 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *GetCleanResponse) GetSeen() []int32 {
	if x != nil {
		return x.Seen
	}
	return nil
}

type ServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Water         bool                   `protobuf:"varint,1,opt,name=water,proto3" json:"water,omitempty"`
	Fileter       bool                   `protobuf:"varint,2,opt,name=fileter,proto3" json:"fileter,omitempty"`
	OutOfSleeves  bool                   `protobuf:"varint,3,opt,name=out_of_sleeves,json=outOfSleeves,proto3" json:"out_of_sleeves,omitempty"`
	NewSleeves    bool                   `protobuf:"varint,4,opt,name=new_sleeves,json=newSleeves,proto3" json:"new_sleeves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRequest) Reset() {
	*x = ServiceRequest{}
	mi := &file_recordcleaner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRequest) ProtoMessage() {}

func (x *ServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recordcleaner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRequest.ProtoReflect.Descriptor instead.
func (*ServiceRequest) Descriptor() ([]byte, []int) {
	return file_recordcleaner_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceRequest) GetWater() bool {
	if x != nil {
		return x.Water
	}
	return false
}

func (x *ServiceRequest) GetFileter() bool {
	if x != nil {
		return x.Fileter
	}
	return false
}

func (x *ServiceRequest) GetOutOfSleeves() bool {
	if x != nil {
		return x.OutOfSleeves
	}
	return false
}

func (x *ServiceRequest) GetNewSleeves() bool {
	if x != nil {
		return x.NewSleeves
	}
	return false
}

type ServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceResponse) Reset() {
	*x = ServiceResponse{}
	mi := &file_recordcleaner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceResponse) ProtoMessage() {}

func (x *ServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recordcleaner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceResponse.ProtoReflect.Descriptor instead.
func (*ServiceResponse) Descriptor() ([]byte, []int) {
	return file_recordcleaner_proto_rawDescGZIP(), []int{4}
}

var File_recordcleaner_proto protoreflect.FileDescriptor

const file_recordcleaner_proto_rawDesc = "" +
	"\n" +
	"\x13recordcleaner.proto\x12\rrecordcleaner\"\x93\x05\n" +
	"\x06Config\x12P\n" +
	"\x0flast_clean_time\x18\x01 \x03(\v2(.recordcleaner.Config.LastCleanTimeEntryR\rlastCleanTime\x12#\n" +
	"\rcurrent_count\x18\x02 \x01(\x05R\fcurrentCount\x12\x1d\n" +
	"\n" +
	"last_water\x18\x03 \x01(\x03R\tlastWater\x12\x1f\n" +
	"\vlast_filter\x18\x04 \x01(\x03R\n" +
	"lastFilter\x12\x1e\n" +
	"\vday_of_year\x18\x05 \x01(\x05R\tdayOfYear\x12\x1b\n" +
	"\tday_count\x18\x06 \x01(\x05R\bdayCount\x12(\n" +
	"\x10current_box_pick\x18\a \x01(\x05R\x0ecurrentBoxPick\x12Y\n" +
	"\x12day_category_count\x18\b \x03(\v2+.recordcleaner.Config.DayCategoryCountEntryR\x10dayCategoryCount\x12.\n" +
	"\x13last_relevant_clean\x18\t \x01(\x03R\x11lastRelevantClean\x123\n" +
	"\x16non_pre_validate_clean\x18\n" +
	" \x01(\x05R\x13nonPreValidateClean\x12$\n" +
	"\x0eout_of_sleeves\x18\v \x01(\bR\foutOfSleeves\x1a@\n" +
	"\x12LastCleanTimeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aC\n" +
	"\x15DayCategoryCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\x0fGetCleanRequest\x12!\n" +
	"\finclude_seen\x18\x01 \x01(\bR\vincludeSeen\x12%\n" +
	"\x0eonly_essential\x18\x02 \x01(\bR\ronlyEssential\x12\x12\n" +
	"\x04peek\x18\x03 \x01(\bR\x04peek\"G\n" +
	"\x10GetCleanResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\x05R\n" +
	"instanceId\x12\x12\n" +
	"\x04seen\x18\x02 \x03(\x05R\x04seen\"\x87\x01\n" +
	"\x0eServiceRequest\x12\x14\n" +
	"\x05water\x18\x01 \x01(\bR\x05water\x12\x18\n" +
	"\afileter\x18\x02 \x01(\bR\afileter\x12$\n" +
	"\x0eout_of_sleeves\x18\x03 \x01(\bR\foutOfSleeves\x12\x1f\n" +
	"\vnew_sleeves\x18\x04 \x01(\bR\n" +
	"newSleeves\"\x11\n" +
	"\x0fServiceResponse2\xb1\x01\n" +
	"\x14RecordCleanerService\x12M\n" +
	"\bGetClean\x12\x1e.recordcleaner.GetCleanRequest\x1a\x1f.recordcleaner.GetCleanResponse\"\x00\x12J\n" +
	"\aService\x12\x1d.recordcleaner.ServiceRequest\x1a\x1e.recordcleaner.ServiceResponse\"\x00B-Z+github.com/brotherlogic/recordcleaner/protob\x06proto3"

var (
	file_recordcleaner_proto_rawDescOnce sync.Once
	file_recordcleaner_proto_rawDescData []byte
)

func file_recordcleaner_proto_rawDescGZIP() []byte {
	file_recordcleaner_proto_rawDescOnce.Do(func() {
		file_recordcleaner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recordcleaner_proto_rawDesc), len(file_recordcleaner_proto_rawDesc)))
	})
	return file_recordcleaner_proto_rawDescData
}

var file_recordcleaner_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_recordcleaner_proto_goTypes = []any{
	(*Config)(nil),           // 0: recordcleaner.Config
	(*GetCleanRequest)(nil),  // 1: recordcleaner.GetCleanRequest
	(*GetCleanResponse)(nil), // 2: recordcleaner.GetCleanResponse
	(*ServiceRequest)(nil),   // 3: recordcleaner.ServiceRequest
	(*ServiceResponse)(nil),  // 4: recordcleaner.ServiceResponse
	nil,                      // 5: recordcleaner.Config.LastCleanTimeEntry
	nil,                      // 6: recordcleaner.Config.DayCategoryCountEntry
}
var file_recordcleaner_proto_depIdxs = []int32{
	5, // 0: recordcleaner.Config.last_clean_time:type_name -> recordcleaner.Config.LastCleanTimeEntry
	6, // 1: recordcleaner.Config.day_category_count:type_name -> recordcleaner.Config.DayCategoryCountEntry
	1, // 2: recordcleaner.RecordCleanerService.GetClean:input_type -> recordcleaner.GetCleanRequest
	3, // 3: recordcleaner.RecordCleanerService.Service:input_type -> recordcleaner.ServiceRequest
	2, // 4: recordcleaner.RecordCleanerService.GetClean:output_type -> recordcleaner.GetCleanResponse
	4, // 5: recordcleaner.RecordCleanerService.Service:output_type -> recordcleaner.ServiceResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_recordcleaner_proto_init() }
func file_recordcleaner_proto_init() {
	if File_recordcleaner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recordcleaner_proto_rawDesc), len(file_recordcleaner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recordcleaner_proto_goTypes,
		DependencyIndexes: file_recordcleaner_proto_depIdxs,
		MessageInfos:      file_recordcleaner_proto_msgTypes,
	}.Build()
	File_recordcleaner_proto = out.File
	file_recordcleaner_proto_goTypes = nil
	file_recordcleaner_proto_depIdxs = nil
}
